### ISSUE TITLE
Add Open Source sub-section

### ISSUE THREAD

**Issue by willcl-ark** [kallerosenbaum/btcphilosophy#10]
I think the concept of "Open Source" could be worked in to the doc; perhaps it would fit well into the `Trustlessness` section?

Open source has a number of benefits (and downsides), but primarily it is a large factor in how users (and developers) can begin to trust the software that they run -- which you already mention as being important. In order for users to trust that their wallets will not cause them to lose control of their coins, wallets and associated programs must at the very least be "source available", but ideally fully [Open Source](https://opensource.org/osd).

What follows from these principles at a protocol level is the ability to audit and verify coin supply and schedule, in a trustless manner. Being open source software also permits permissionless development both to the protocol, and on systems and applications on top of it which is a core part of the ideology behind Bitcoin, in my opinion :)

**Comment by kallerosenbaum** [comment]
Yep. We have planned for a "Review" chapter, and I think it could fit in there as well. But "Trustlessness" might work out fine too.

Keeping this open until we can proudly say we've covered Open Source.

**Comment by glozow** [comment]
I agree with this and actually think it should be the first section if this is intended for new developers. Newcomers often experience "culture shock" and chalk it up to there being something wrong with how maintainers do things or "deadness" of the project itself. It might be worth noting _very early on_ that many of our concerns are **nonexistent** in other projects, and reading this might clear that up. When we prioritize decentralization, we obviously sacrifice in other areas. We deem security non-negotiable, which is why we don't have XYZ feature or use ABC dependency. We try to support as many architectures/operating systems as possible; we don't just release a docker container that downloads the binary from a website and call it a day. Deterministic builds are unheard of in other projects but we won't merge a PR if it breaks the guix build.

This might translate well into the decentralization section (or finite supply section if it turns more into a decentralized development decision making section) e.g. every Core maintainer is funded by a different org right now, no company controls project timelines, etc. One of those areas where what you see on the day-to-day ("why is my PR not merged yet") is an intentional, direct product of the priorities.

**Comment by kallerosenbaum** [comment]
I think we should rename the "Review" chapter to "Open Source", thus broadening that chapter and make a "Review" subsection in it.

**Comment by kallerosenbaum** [comment]
I've written a chapter on [open source](https://rosenbaum.se/btcphil/#opensource) now.

(As a side note, we might not write explicitly about every aspect, but many of them are covered by the linked articles, which the reader is expected to read. Our material is merely a nice way to present the linked material and make a few quotes. (There you go, we've freed ourselves from any responsibilities of coverage :smile:)).

I've covered most of your feedback (I think), but it's been done in multiple places, so I'm giving you references to those places below:

@willcl-ark :

> can begin to trust the software that they run

* https://rosenbaum.se/btcphil/#_dont_trust_verify
* resource https://blog.lopp.net/who-controls-bitcoin-core-/

> ability to audit and verify coin supply and schedule

* https://rosenbaum.se/btcphil/#trustlessness (third paragraph)

> permissionless development

* New section "permissionless development" https://rosenbaum.se/btcphil/#_permissionless_development

@glozow :

> Newcomers often experience "culture shock" and chalk it up to there being something wrong with how maintainers do things or "deadness" of the project itself

* I liked the wording "culture shock" so I added a rection about that: https://rosenbaum.se/btcphil/#_culture_shock
* Also touches on this in https://rosenbaum.se/btcphil/#_software_maintenance

> We deem security non-negotiable, which is why we don't have XYZ feature or use ABC dependency.

* https://rosenbaum.se/btcphil/#_libraries
* https://rosenbaum.se/btcphil/#_culture_shock

> Deterministic builds are unheard of in other projects but we won't merge a PR if it breaks the guix build.

* https://rosenbaum.se/btcphil/#_dont_trust_verify (added this resource: https://www.reddit.com/r/Bitcoin/comments/smj1ep/bitcoin_v220_and_guix_stronger_defense_against/)

> Support many architectures

* Ignored

> every Core maintainer is funded by a different org right now

* Ignored

**Comment by kallerosenbaum** [comment]
Closing this. Feel free to reopen if you disagree.
